### PR TITLE
Add span to $form_message for styling

### PR DESCRIPTION
**Pull request by epigeyre**
Adding a span with a class around the $form_message will make styling the message easier on the front-end.

### CODE REVIEW

**Comment by mskochev** [comment]
Hello, thanks for the suggestion. We'll review it.

**Comment by mskochev** [comment]
Please can you rename the class to `mailjet_widget_form_message` in order to be consistent with the other classes used by the plugin.

**Comment by epigeyre** [comment]
Done.

**Comment by epigeyre** [comment]
Well if you don't use it for anything else that's not a problem. I've edited the file.

**Pull request merged**
